### ISSUE TITLE
Type 'String' is not assignable to type 'string'.

### ISSUE THREAD

**Issue by ghost** [GaspardCulis/minescrap#1]
```
╭─mari@torch ~/Desktop/minescrap ‹main●› 
╰─$ npx ts-node src/search.ts -v
/home/mari/Desktop/minescrap/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/search.ts:168:21 - error TS2345: Argument of type '(ip: string, ports: number) => Promise<void>' is not assignable to parameter of type '(ip: String, port: number) => void'.
  Types of parameters 'ip' and 'ip' are incompatible.
    Type 'String' is not assignable to type 'string'.
      'string' is a primitive, but 'String' is a wrapper object. Prefer using 'string' when possible.

168 masscan.on("found", async (ip: string, ports: number) => {
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/home/mari/Desktop/minescrap/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/home/mari/Desktop/minescrap/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/home/mari/Desktop/minescrap/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/home/mari/Desktop/minescrap/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/home/mari/Desktop/minescrap/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.require.extensions.<computed> [as .ts] (/home/mari/Desktop/minescrap/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12) {
  diagnosticCodes: [ 2345 ]
}

I am hoping someone knows whats going on since I don't understand why it's doing this.

**Comment by GaspardCulis** [comment]
Hi, it was an issue with my node-masscan library. It's been fixed now so update your node_modules to have the 1.1.4 version of node-masscan.
